### ISSUE TITLE
This is not working now!!

### ISSUE THREAD

**Issue by RameshHB123** [GroenteLepel/qiskit-quantum-knn#15]
Since the qiskit aqua is depricated now, this code is not working anymore. Can somebody please help me in implementing this QKNN with latest qiskit libraries.

**Comment by chin-jey** [comment]
[Here](https://github.com/mspronesti/qlearnkit) you can find a quantum knn (looks a different implementation)

**Comment by RameshHB123** [comment]
Hi , thanks for the reply.

Btw, with this one, I'm getting error in encoding_map = AmplitudeEncoding(n_features = 2)


I'm not understanding how to resolve this one, can you please once look into it and get back to me.

Thanks & regards,

Ramesh H B

Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ErmachenkoBoris** [comment]
Fixed, Now this working.

**Comment by dthebala** [comment]
Is it fixed for anyone who installs it through pip? I am still receiving the _module not found_ error with qiskit.aqua

**Comment by dthebala** [comment]
> [Here](https://github.com/mspronesti/qlearnkit) you can find a quantum knn (looks a different implementation)

@chin-jey  I see the following output when running `pip install qlearnkit`

error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by manvirvirk** [comment]
Hi, it is taking too long to predict. my data shape is(288,10). Can anyone help?
